excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://subhroinindia.github.io
title: A Day in the Life
tagline: A log of everyday life
description: My awesome new site
paginate: 5